### ISSUE TITLE
KQUEUE_LOOP-non_blocking

### ISSUE THREAD

**Issue by Zangetsu89** [Zangetsu89/webserve#63]
Currently reading request data in a loop which potentially blocks other sockets from READ/WRITE until this request is fully read. Need to update this function to read in a non-blocking manner, meaning no (loop and sleep() ).

**Comment by Tatamize** [comment]
I modified to call one "read" function in kqueue loop, if the data reading is not finished, new filter is set and kqueue catches the event again (until all data is read).
